
server:
  port: 9001
spring:
  application:
    name: feign-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/